# Render configuration for Strip Photobooth Backend
services:
  # Backend API Service
  - type: web
    name: strip-photobooth-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    
    # Environment variables (set these in Render dashboard)
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # Set in Render dashboard
      - key: CLOUDINARY_CLOUD_NAME
        sync: false  # Set in Render dashboard
      - key: CLOUDINARY_API_KEY
        sync: false  # Set in Render dashboard
      - key: CLOUDINARY_API_SECRET
        sync: false  # Set in Render dashboard

    
    # Auto-deploy settings
    autoDeploy: true
    
    # Build settings
    buildFilter:
      paths:
        - backend/**
      ignoredPaths:
        - frontend/**
        - README.md
        - .gitignore
    
    # Health check settings
    healthCheckPath: /api/health
    
    # Scaling settings
    numInstances: 1
    
    # Disk storage
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1

# Database (if using Render's MongoDB - optional)
databases:
  - name: strip-photobooth-db
    databaseName: strip_photobooth
    user: strip_user
    region: oregon
    plan: free
    version: "6.0"

# Static site (alternative to Netlify - optional)
# - type: static
#   name: strip-photobooth-frontend
#   buildCommand: cd frontend && npm ci && npm run build
#   staticPublishPath: frontend/build
#   pullRequestPreviewsEnabled: true
#   
#   envVars:
#     - key: REACT_APP_API_URL
#       value: https://strip-photobooth-api.onrender.com
#   
#   buildFilter:
#     paths:
#       - frontend/**
#     ignoredPaths:
#       - backend/**
