# Additional Netlify configuration for consistent URL
# This ensures your site URL remains constant

[site]
  # Force consistent site name (optional - set in Netlify dashboard)
  name = "strip-photobooth"

[build]
  # Prevent rebuilds for documentation changes
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- README.md DEPLOYMENT.md docs/"
